### ISSUE TITLE
startup error 

### ISSUE THREAD

**Issue by vitos88** [LibreCodeCoop/whatsapp-client#19]
I get an error
`[root@ovz1 ovz1.test.m29on.vps.myjino.ru]# docker-compose up -d
ovz1testm29onvpsmyjinoru_selenium-hub_1 is up-to-date
ovz1testm29onvpsmyjinoru_firefox_1 is up-to-date
ovz1testm29onvpsmyjinoru_php7_1 is up-to-date
ovz1testm29onvpsmyjinoru_chrome_1 is up-to-date
[root@ovz1 ovz1.test.m29on.vps.myjino.ru]# docker-compose exec php7 php example.php

Fatal error: Uncaught RuntimeException: "" does not implement "Facebook\WebDriver\JavaScriptExecutor". in /whatsapp/vendor/symfony/panther/src/Client.php on line 473

Call Stack:
   30.3446    3309464   1. Monolog\ErrorHandler->handleException() /whatsapp/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:0

RuntimeException: "" does not implement "Facebook\WebDriver\JavaScriptExecutor". in /whatsapp/vendor/symfony/panther/src/Client.php on line 473

Call Stack:
   30.3446    3309464   1. Monolog\ErrorHandler->handleException() /whatsapp/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:0
   30.5198    3283080   2. WhatsappClient\TelegramClient->__destruct() /whatsapp/src/Client.php:0
   30.5198    3283080   3. Symfony\Component\Panther\Client->executeScript() /whatsapp/src/Client.php:175

`
help please I do not know what it is connected with

**Comment by alexeykirichek** [comment]
I stopped at the same problem. Did you manage to solve it?

**Comment by vitormattos** [comment]
This is a test project and no more used. If you want contribute, bug fixes are welcome.

**Comment by aroyalheart** [comment]
Same issue

**Comment by vitormattos** [comment]
I did tests without errors.

Updated dependencies.
